## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999
codecov: true
matrix:
  allow_failures:
    - julia: nightly
      os: linux
